name: T Group
favicon: null
layout_spectrum: 0.02889
typography_spectrum: 0.13786
title: T Group Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#343434'
    - '#d56263'
    - '#808080'
    - '#ff0000'
  brandStrength: 0.8125
  lightness: 0.7638370003551245
  saturation: 0.6086278315633535
  rhythmicContrast: 0.6599805951118469
purpose: []
